### ISSUE TITLE
configparser.NoOptionError: No option 'db_url' in section: 'DEFAULT'

### ISSUE THREAD

**Issue by recallmenot** [rseichter/fangfrisch#45] opened 2024-07-01 07:39 UTC
Hi, trying to run `fangfrisch refresh`, I get the error below.
OS: Manjaro, up-to-date
Python: 3.12
installed from [AUR](https://aur.archlinux.org/packages/python-fangfrisch) via yay

```
fangfrisch refresh
Traceback (most recent call last):
  File "/usr/lib/python3.12/configparser.py", line 767, in get
    value = d[option]
            ~^^^^^^^^
  File "/usr/lib/python3.12/collections/__init__.py", line 1015, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/collections/__init__.py", line 1007, in __missing__
    raise KeyError(key)
KeyError: 'db_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fangfrisch", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/fangfrisch/__main__.py", line 65, in main
    DbMeta.assert_version_match()
  File "/usr/lib/python3.12/site-packages/fangfrisch/db.py", line 78, in assert_version_match
    DbMeta.init(False)
  File "/usr/lib/python3.12/site-packages/fangfrisch/db.py", line 63, in init
    db_url = config.db_url()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/fangfrisch/config/config.py", line 96, in db_url
    return self.parser.get(configparser.DEFAULTSECT, DB_URL)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/configparser.py", line 770, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'db_url' in section: 'DEFAULT'
```

**Comment by rseichter** [comment] 2024-07-01 16:02
The secret sauce is in the error message. See the last line of text there, and the first line in the documentation's [chapter 5](https://rseichter.github.io/fangfrisch/#_configuration). 😉

Closing issue, not a bug.

**Closed by rseichter** 2024-07-01 16:02 UTC
