### ISSUE TITLE
urlhaus digest mismatch

### ISSUE THREAD

**Issue by ttrueten** [rseichter/fangfrisch#9] opened 2020-11-27 09:55 UTC
The v3.7.3 Script runs well but sometimes (for ex. today, Fri, 27 Nov 2020 10:45:03 ) I get odd messages in the log file / status mail like:
WARNING: https://urlhaus.abuse.ch/downloads/urlhaus.ndb sha256 digest mismatch (expected fc554db6a3a6d2fee4056a0b80d4724a4701dc100f7034c80c75c41ce382963f, got 8ff4b8d6c964ed579bdba6fc1931382daed2d567d70e7e26f20b4d240abd1797)
Seems to be due to urlhaus, but I don't necessarily want to switch off the checksum checks completely.
So, any hint's?

**Comment by rseichter** [comment] 2020-11-27 18:21
Urlhaus is aware of this issue since February 2020. I was told that the reason is the large number of generated file versions (one per minute). This frequency apparently clashes with the limited number of API calls, and clearing the CDN cache requires such calls. This is an issue only Urlhaus can fix. Perhaps you could contact Urlhaus staff yourself, to indicate that you are interested in a solution?

I will close this GitHub issue, because I cannot do anything about it myself.

**Comment by rseichter** [comment] 2023-06-03 04:24
It has been an issue on Urlhaus' end for so long that I was pretty much resigned to shrug it off as a "that's life" kind of thing. They have been kind enough to provide a checksum after I asked for it three years ago, for which I am grateful. Still, I agree that the checksum files not being reliably updated greatly reduces their benefits.

It is possible to implement a workaround, but would it really be useful to hide the symptom instead of Urlhaus addressing the root cause? Perhaps it would help if you and other users petitioned politely to fix it underlying problem on their side? Their service is much appreciated, and all we can do is ask nicely, because Urlhaus obviously does not owe us anything.

**Comment by rseichter** [comment] 2023-06-09 20:26
I hope that Urlhaus will respond to your inquiry. For the time being, I will close this issue once more.

**Closed** 2023-06-09 20:27 UTC

**Comment by Stevehans** [comment] 2026-01-19 09:24
Same issue in 2026, I'm being battered by alerts.

I'll disable the checksum checking

**Comment by rseichter** [comment] 2026-01-19 11:54
For what it's worth, the following settings work for me most of the time. By that I mean checksum mismatches are rarely reported more than once a day.

```
[urlhaus]
enabled = yes
interval = 5m
```
